### ISSUE TITLE
IntOrString.toJson

### ISSUE THREAD

**Issue by kaaninel** [xclud/dart_kubernetes#5]
toJson implementation is missing in IntOrString class so while creating a Service json serialization throw an error. As a workaround I'm extending this class and using that instead. 

```dart
class IntOrStringJSON extends IntOrString {
  IntOrStringJSON(super.value);
  Object toJson() => value;
}
```

I'm not sure if this project is still maintained so I didn't create a pull request but I can if @xclud is interested.

**Comment by xclud** [comment]
Hi.
Thanks for the suggestion. Please do the PR.

**Comment by kaaninel** [comment]
Please check #6

**Comment by xclud** [comment]
Merged!
